### ISSUE TITLE
Negative coordinates point towards our side of the field

### ISSUE THREAD

**Issue by Wanchai290** [NAMeC-SSL/CRAbE#89]
Mentioned in #75 

This is the feature that makes it so positive coordinates are towards the enemy's side of the field, and negative coordinates are towards our side of the field. Such a filter requires rigorous testing to avoid angular orientation problems for example (although it seems to have worked well during the RoboCup 2023).

It is some kind of pre filter or post filter if I recall correctly.

**Comment by Jossl123** [comment]
i'm on it
